apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-demo
  namespace: spa-demo
  labels:
    app: spa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-demo
  template:
    metadata:
      labels:
        app: spa-demo
    spec:
      containers:
      - name: spa-demo
        imagePullPolicy: IfNotPresent
        image: docker.io/toucansoftware/spa-reloader-demo:v1
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spa-demo
  namespace: spa-demo
  labels:
    app: spa-demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: spa-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spa-demo
  namespace: spa-demo
  labels:
    app: spa-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spa-demo
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: spa-reloader
            port:
              number: 8080
